### ISSUE TITLE
Add `extends` field

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/tomcab#3]
```toml
extends = ["../base.toml"]

name = "example"
```
Useful for monorepos with multiple projects that want to share common stanzas. Should act the same as common stanza imports, except for the entire Package file.

TODO: should this be in the `tomcab` section, or is it special enough?
