### ISSUE TITLE
Support module patterns in conditionals

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/tomcab#8]
```toml
exposed-modules = ["Foo.*"]
other-modules = ["Foo.Bar.*"]
[[if]]
condition = "impl(ghc > 8)"
exposed-modules = ["Foo.Bar.Baz"]
```
should generate
```cabal
exposed-modules: Foo, Foo.Example
other-modules: Foo.Bar, Foo.Bar.Example
if impl(ghc > 8)
  exposed-modules: Foo.Bar.Baz
```
Rule: For a given module, find the closest matching pattern among _all_ patterns
